### ISSUE TITLE
TECH DEPT: Update Smart-ID test parameters

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#205]
**What?**

We have an API test that is consantly failing and thus disrupt release process.
The problem is not in the test itself, but probably configuration changes on SK side.

  ```
  1) Users
       Topics
         Votes
           Vote
             authType === hard
               Smart-ID
                 Fail - 40010 - User has cancelled the signing process Latvian PID:
     Error: expected 200 "OK", got 400 "Bad Request"
      at Test._assertStatus (/home/m/dev/citizenos-api/node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (/home/m/dev/citizenos-api/node_modules/supertest/lib/test.js:283:11)
      at Test.assert (/home/m/dev/citizenos-api/node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (/home/m/dev/citizenos-api/node_modules/supertest/lib/test.js:131:12)
      at Object.onceWrapper (events.js:286:20)
      at Server.emit (events.js:198:13)
      at Server.EventEmitter.emit (domain.js:448:20)
      at emitCloseNT (net.js:1619:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**TODO**

* Make it so that the test is valid and passes.

**Comment by ilmartyrk** [comment]
Issue is down to certificate returned by demo API that has expired 30.08.2020. Sent an e-mail with data and API endpoint, hopefully it is a quick fix from them

**Comment by ilmartyrk** [comment]
Recieved an answer today:

Hetkel praegu seda kontot ei pikendata. See vanem lahendus suletakse sel aastal (augustis eeldatavalt).
Praegu palume siis kasutada uusi numbreid.

**Comment by loorm** [comment]
Triage 37. Estimated dev time 0.5 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
This task should be altered to include updating all Smart-ID tests with new parameters https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#accounts

**Comment by ilmartyrk** [comment]
Fixed with https://github.com/citizenos/citizenos-api/commit/f414654706f836f79ae394f3936d05b020a97508 as I needed to be sure all tests pass
